"""The scrub pads, from the generator's copper onto the board. Re-runnable.

    KPY=/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/3.9/bin/python3
    $KPY hardware/faceplate/design/mkpads.py            # footprint + board
    python3 hardware/faceplate/design/mkpads.py --lib   # footprint only, no pcbnew

Two steps, both derived from mockups/generate-faceplate.py copper(), never typed:

  1. Footprints SCRUB_PAD_216x10_P1..P4 in the shared vuulgaris.pretty, one
     per pad, origin at its centre: the four are not identical, because vias
     and bridges near J1 differ (generator via_keepouts_mm). Every bar is a roundrect SMD pad on F.Cu with
     the generator's own fillet; every sliver bridge a rect pad overlapping the
     two bars it joins. Pads are numbered by E's symbol pins: RX0 is pin 1 at
     the start of the pad (x < centre) and pin 5 at the end, RX1-RX3 pins 2-4,
     so boardcheck sees every bar on its PADp_RXn net. No F.Paste: the stencil
     would otherwise paste the whole scrub surface. One F.Mask opening over the
     whole pad (per-pad openings would leave 0.01mm mask dams in the 0.21mm
     tooth gaps), and a B.Mask opening at every via so the vias are open at both
     ends (ADR 0003: not filled, not capped, and not tented on one side, which
     would trap plating chemistry). Excluded from BOM and placement files, and
     allowed to bridge its own nets under that one mask opening -- which is
     the point of it.

  2. The board, through pcbnew. E1-E4 on F.Cu at the generator's pad centres,
     every pad's net from netmap.json, and one through via per bar at the
     generator's via point, on that bar's net. Idempotent: removes E1-E4 and
     every via on a PADp_RXn net first. Vias are board items because KiCad 7
     footprints cannot hold them.

After this writes the board, File -> Revert in Pcbnew before touching it.
"""
import json
import math
import os
import sys
import uuid

HERE = os.path.dirname(os.path.abspath(__file__))
FACE = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(os.path.dirname(FACE), "kicad", "tools"))
sys.argv[1:1] = ["--project", "faceplate"]
import proj            # noqa: E402
import panelgeo as pg  # noqa: E402

P = proj.P
LIB = os.path.join(proj.PROJECTS["main"].dir, "lib", "vuulgaris.pretty")
NAME = lambda p: f"SCRUB_PAD_216x10_P{p}"
FP_PATH = lambda p: os.path.join(LIB, NAME(p) + ".kicad_mod")
MASK_MARGIN = pg.PAD_MASK_MARGIN   # F.Mask opening beyond the copper, all round (0.25;
                                   # the silkscreen keeps clear of it, panelgeo.panel_silk())
VIA_MASK = 0.1          # B.Mask opening beyond the via pad, on diameter

gen, G = pg.generator()
C = dict(gen.CFG)


def pin(net, x):
    """E symbol pin for a bar: RX0 is 1 before the pad centre, 5 after."""
    if net == 0:
        return "1" if x < G["PAD_MID"] else "5"
    return str(net + 1)


def local_copper(p):
    """copper() for pad p, and its origin (the pad centre) in panel mm."""
    y0 = G["PAD_TOPS"][p - 1]
    cu = gen.copper(C, G, y0)
    ox, oy = G["PAD_MID"], y0 + G["PW"] / 2.0
    return cu, ox, oy


def f(v):
    return f"{v:.4f}".rstrip("0").rstrip(".")


def footprint(p):
    cu, ox, oy = local_copper(p)
    PL, PW = G["PL"], G["PW"]
    L = [f'(footprint "{NAME(p)}" (version 20221018) (generator mkpads)',
         '  (layer "F.Cu")',
         f'  (descr "Vuulgaris scrub pad {p}, {PL:g} x {PW:g}mm, {G["N_TEETH"]} ratio-encoded comb '
         f'teeth (ADR 0003). GENERATED by hardware/faceplate/design/mkpads.py from '
         f'mockups/generate-faceplate.py copper(); do not edit. Bars are pads numbered by the '
         f'SCRUB_PAD_5SEG pins (RX0 = 1 and 5, RX1-RX3 = 2-4); each takes an open via placed on '
         f'the board by mkpads.py.")',
         '  (attr smd exclude_from_pos_files exclude_from_bom allow_soldermask_bridges)',
         f'  (fp_text reference "REF**" (at 0 {f(-PW / 2 - 1.5)}) (layer "F.Fab") hide'
         '\n    (effects (font (size 1 1) (thickness 0.15))))',
         f'  (fp_text value "{NAME(p)}" (at 0 {f(PW / 2 + 1.5)}) (layer "F.Fab") hide'
         '\n    (effects (font (size 1 1) (thickness 0.15))))']
    hx, hy = PL / 2.0, PW / 2.0
    L.append(f'  (fp_rect (start {f(-hx)} {f(-hy)}) (end {f(hx)} {f(hy)}) '
             '(stroke (width 0.1) (type solid)) (fill none) (layer "F.Fab"))')
    m = MASK_MARGIN
    L.append(f'  (fp_rect (start {f(-hx - m)} {f(-hy - m)}) (end {f(hx + m)} {f(hy + m)}) '
             '(stroke (width 0) (type solid)) (fill solid) (layer "F.Mask"))')
    L.append(f'  (fp_rect (start {f(-hx - m - 0.25)} {f(-hy - m - 0.25)}) '
             f'(end {f(hx + m + 0.25)} {f(hy + m + 0.25)}) '
             '(stroke (width 0.05) (type solid)) (fill none) (layer "F.CrtYd"))')
    vd = C["via_dia_mm"] + VIA_MASK
    for _, x, y in cu["vias"]:
        L.append(f'  (fp_circle (center {f(x - ox)} {f(y - oy)}) (end {f(x - ox + vd / 2)} {f(y - oy)}) '
                 '(stroke (width 0) (type solid)) (fill solid) (layer "B.Mask"))')
    for net, x, y, w, h in cu["bars"]:
        r = gen.bar_r(C, w, h)
        L.append(f'  (pad "{pin(net, x)}" smd roundrect (at {f(x + w / 2 - ox)} {f(y + h / 2 - oy)}) '
                 f'(size {f(w)} {f(h)}) (layers "F.Cu" "F.Mask") '
                 f'(roundrect_rratio {r / min(w, h):.6f}))')
    for net, x, y, w, h in cu["bridges"]:
        L.append(f'  (pad "{pin(net, x + w / 2)}" smd rect (at {f(x + w / 2 - ox)} {f(y + h / 2 - oy)}) '
                 f'(size {f(w)} {f(h)}) (layers "F.Cu" "F.Mask"))')
    L.append(")")
    return "\n".join(L) + "\n"


def write_lib():
    for p in range(1, 5):
        txt = footprint(p)
        old = open(FP_PATH(p)).read() if os.path.exists(FP_PATH(p)) else None
        if old != txt:
            open(FP_PATH(p), "w").write(txt)
        cu, _, _ = local_copper(p)
        print(f"{NAME(p)}: {len(cu['bars'])} bars, {len(cu['bridges'])} bridges, "
              f"{len(cu['vias'])} vias{'' if old != txt else ' (unchanged)'}")


def place():
    import pcbnew
    mm = pcbnew.FromMM
    nm = json.load(open(P.netmap))
    b = pcbnew.LoadBoard(P.pcb)
    refs = {f"E{p}" for p in range(1, 5)}
    padnets = {f"/{n}" for r in refs for n in nm[r].values()}
    # Collect before removing anything: in KiCad 7's bindings b.Tracks() stops
    # being iterable once a footprint has been removed from the board.
    old_vias = [t for t in b.GetTracks()
                if isinstance(t, pcbnew.PCB_VIA) and t.GetNetname() in padnets]
    old_fps = [fp for fp in b.GetFootprints() if fp.GetReference() in refs]
    for t in old_vias:
        b.Remove(t)
    for fp in old_fps:
        b.Remove(fp)

    def net(name):
        n = b.FindNet(name)
        if n is None:
            n = pcbnew.NETINFO_ITEM(b, name)
            b.Add(n)
        return n

    nv = 0
    for p in range(1, 5):
        ref = f"E{p}"
        cu, ox, oy = local_copper(p)
        fp = pcbnew.FootprintLoad(LIB, NAME(p))
        fp.SetFPID(pcbnew.LIB_ID("vuulgaris", NAME(p)))
        fp.SetReference(ref)
        fp.SetValue(NAME(p))
        cx, cy = pg.face_sheet((ox, oy))
        b.Add(fp)
        fp.SetPosition(pcbnew.VECTOR2I(mm(cx), mm(cy)))
        for pad in fp.Pads():
            pad.SetNet(net("/" + nm[ref][pad.GetNumber()]))
        for n, x, y in cu["vias"]:
            v = pcbnew.PCB_VIA(b)
            b.Add(v)
            v.SetViaType(pcbnew.VIATYPE_THROUGH)
            v.SetLayerPair(pcbnew.F_Cu, pcbnew.B_Cu)
            sx, sy = pg.face_sheet((x, y))
            v.SetPosition(pcbnew.VECTOR2I(mm(sx), mm(sy)))
            v.SetWidth(mm(C["via_dia_mm"]))
            v.SetDrill(mm(C["via_drill_mm"]))
            v.SetNet(net("/" + nm[ref][pin(n, x)]))
            nv += 1
    pcbnew.ZONE_FILLER(b).Fill(b.Zones())
    pcbnew.SaveBoard(P.pcb, b)
    print(f"board: E1-E4 placed, {nv} vias. File -> Revert in Pcbnew before touching it.")


if __name__ == "__main__":
    write_lib()
    if "--lib" not in sys.argv:
        place()
