#!/usr/bin/env python3
"""Which KiCad project a loop tool is working on.

The loop tools -- mksch, netcheck, drc, boardcheck, ksym -- serve both boards.
They default to the main board, so every command in CLAUDE.md runs unchanged,
and the faceplate is one flag away:

    python3 tools/mksch.py --project faceplate && python3 tools/netcheck.py --project faceplate
    python3 tools/drc.py --project faceplate

Importing this module TAKES `--project NAME` out of sys.argv, so a tool's own
argument handling never sees it. That matters: boardcheck.py and drc.py both
read a bare positional argument as a board path, and would otherwise try to
open a file called "faceplate".

What differs between projects is only where things live. Each project has a
DATA directory holding its intent and its schematic design:

    netmap.json   the intent: every (ref, pin) that carries a net
    values.json   Value field per ref, optional
    design.py     SYM / POS / FPMAP / LIBS -- which symbol, where on the sheet,
                  which footprint. Read by mksch.py.
    kpins.json    pin geometry cache, generated by ksym.py, untracked

The main board's data directory is tools/, for history's sake; the faceplate's
is hardware/faceplate/design/.
"""
import os
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
HW = os.path.dirname(os.path.dirname(TOOLS))            # hardware/


class Project:
    def __init__(self, key, subdir, name, data):
        self.key = key
        self.dir = os.path.join(HW, subdir)
        self.name = name                                  # KiCad file basename
        self.data = os.path.join(self.dir, data)
        self.sch = os.path.join(self.dir, f"{name}.kicad_sch")
        self.pcb = os.path.join(self.dir, f"{name}.kicad_pcb")
        self.pro = os.path.join(self.dir, f"{name}.kicad_pro")
        self.drc_rpt = os.path.join(self.dir, "DRC.rpt")
        self.netmap = os.path.join(self.data, "netmap.json")
        self.values = os.path.join(self.data, "values.json")
        self.design = os.path.join(self.data, "design.py")
        self.kpins = os.path.join(self.data, "kpins.json")


PROJECTS = {
    "main":      Project("main", "kicad", "vuulgaris", "tools"),
    "faceplate": Project("faceplate", "faceplate", "vuulgaris-faceplate", "design"),
}


def _take_project_arg(argv):
    for i, a in enumerate(argv[1:], 1):
        if a == "--project":
            if i + 1 >= len(argv):
                sys.exit(f"--project needs a name: {', '.join(PROJECTS)}")
            key = argv[i + 1]
            del argv[i:i + 2]
            return key
        if a.startswith("--project="):
            del argv[i]
            return a.split("=", 1)[1]
    return "main"


KEY = _take_project_arg(sys.argv)
if KEY not in PROJECTS:
    sys.exit(f"--project {KEY!r}: expected one of {', '.join(PROJECTS)}")
P = PROJECTS[KEY]
