/*
 * Vuulgaris V1 - faceplate touch firmware
 * MSP430FR2675TPTR (CapTIvate), 48-pin LQFP (PT)
 *
 * Skeleton. Reads four capacitive scrub sliders and reports position to the Daisy.
 *
 * The CapTIvate sensor configuration is NOT written here. It is generated by
 * CapTIvate Design Center into ../../captivate/generated/ and included below.
 * Do not hand-edit generated files.
 *
 * See docs/pin-assignment.md before changing anything about electrode order.
 */

#include <msp430.h>

/* Generated by CapTIvate Design Center. Regenerate, never edit. */
/* #include "CAPT_App.h"      */
/* #include "CAPT_UserConfig.h" */

#define NUM_PADS 4

/* Latest position per pad, 0..(resolution-1) across 175mm.
 *
 * Resolution is configured in Design Center. 1000 gives 0.175mm per step, which is well
 * beyond 10-bit. But the real limit is JITTER, not resolution: if this value wanders N
 * counts at rest, usable positions = resolution / N. Measure it before choosing any
 * filtering, and log it in tuning/.
 */
static volatile unsigned int  pad_position[NUM_PADS];
static volatile unsigned char pad_touched[NUM_PADS];

static void LinkInit(void)
{
    /* TODO: eUSCI_A as UART to the Daisy. eUSCI_B as I2C is the fallback.
     *
     * UNVERIFIED, and it blocks PCB layout: eUSCI_A and eUSCI_B may share physical port
     * pins on the PT package. If they do, the board needs 0R jumpers to select between
     * them. Pull the FR2675 datasheet pin function table.
     * See ../../docs/pin-assignment.md and docs/notes/open-questions.md Q2.
     */
}

static void IrqInit(void)
{
    /* TODO: assert a GPIO when a new frame of positions is ready, so the Daisy does not
     * poll. Deassert on read.
     */
}

static void ReportPositions(void)
{
    /* TODO: pack NUM_PADS positions + touch flags, send over the link, raise IRQ.
     *
     * Keep the frame small and fixed-length. The Daisy reads this inside a real-time
     * audio application, so a variable-length parse is a liability.
     */
}

int main(void)
{
    WDTCTL  = WDTPW | WDTHOLD;
    PM5CTL0 &= ~LOCKLPM5;      /* unlock GPIO after LPMx.5 */

    LinkInit();
    IrqInit();

    /* TODO: CAPT_appStart() once the Design Center project is generated. */

    while(1)
    {
        /* TODO:
         *   CAPT_appHandler();
         *   read slider positions into pad_position[] / pad_touched[]
         *   ReportPositions() when they change
         *
         * Note: two fingers on one pad reads as a single averaged position, and there is
         * no palm rejection with exposed copper. Accepted limitation, see ADR 0003.
         */
        __no_operation();
    }
}
